spring.application.name=nameserver

server.port=8761

# O server não se autoregistrar no discovery
eureka.client.register-with-eureka=false

# Não baixar a lista de serviços eureka - o proprio serviço é responsavel por mante-la/gerencia-la
eureka.client.fetch-registry=false

# Indicar para o servodor registrar o IP do serviço e não o nome de dominio
eureka.instance.prefer-ip-address=true

